---
name: 'publish-docker'
description: 'create, tag and push docker container'
inputs:
  
  docker-context:
    description: 'Dockerfile location'
    required: false
    default: .

  docker-registry:
    description: 'Docker registry name'
    required: false
    default: ghcr.io

  docker-platforms:
    description: 'Docker platform for compilation'
    required: false
    default: linux/amd64,linux/arm64

  docker-push:
    description: 'Push to docker registry'
    required: false
    default: true

  docker-image:
    description: 'Complete docker image name'
    required: true

  username:
    description: 'Name of user for container registry'
    required: true

  password:
    description: 'Password container registry'
    required: true

outputs:
  version-tag:
    description: "Generated SemVer tag"
    value: ${{ steps.get-semver.outputs.TAGVERSION }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get semver 2.0 Version tag
      id: get-semver
      shell: bash
      run: |
        TAG=$(docker run --rm -v "$(pwd)":/git-semver mdomke/git-semver -no-meta)
        echo "::set-output name=TAGVERSION::$(echo $TAG)"
        echo "$TAG"
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.docker-image }}
        flavor: |
          latest=true
        tags: |
          type=semver,pattern={{version}},value=${{ steps.get-semver.outputs.TAGVERSION }}
          type=semver,pattern={{major}}.{{minor}},value=${{ steps.get-semver.outputs.TAGVERSION }}
          type=semver,pattern={{major}},value=${{ steps.get-semver.outputs.TAGVERSION }}
          type=ref,event=tag
          type=sha,prefix=
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
  
    - name: Login to Github Container
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.docker-registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    
    - name: Build and push docker immage
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.docker-context }}
        platforms: ${{ inputs.docker-platforms }} 
        push: ${{ inputs.docker-push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}