---
name: Test Code Base

on:
  push:
    branches: 
      - main
  
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    # Name the Job
    name: Test action behaviour
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      # run the action
      - name: Run publish-docker
        id: run-publish-docker
        uses: lucenelletenebre/publish-docker@main
        with:
          docker-context: ./test
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          docker-image: ghcr.io/lucenelletenebre/test
          docker-platforms: linux/amd64

      # download the just created and uploaded image
      - name: RUN "Hello world" container
        id: test-data
        run: |
          RES=$(docker run --rm ghcr.io/lucenelletenebre/test:${{ steps.run-publish-docker.outputs.version-tag}})
          echo "::set-output name=value::$RES"
      
      # verify that the container works as expected
      - name: Verify results
        uses: nick-fields/assert-action@v1
        with:
          expected: Hello_World_from_action
          actual: ${{ steps.test-data.outputs.value }}
          comparison: exact
      