---
name: Test Code Base

on:
  push:
    branches: 
      - main
  
  # pull_request:
  #   branches:
  #     - main

  workflow_dispatch:

jobs:
  test:
    # Name the Job
    name: Test action behaviour
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:

      # remove older unused images
      - name: Clean older unused docker images
        uses: vlaurin/action-ghcr-prune@v0.4.0
        with:
          token: ${{ secrets.PAT }}
          container: test
          dry-run: false # Dry-run first, then change to `false`
          older-than: 1 # days
          keep-last: 0
          untagged: true
      
      # # get the branch name that triggered the action
      # - name: Git branch name
      #   uses: EthanSK/git-branch-name-action@v1
      # # output is env.GIT_BRANCH_NAME

      # - name: Show Branch name
      #   run: |
      #     echo ${{ env.GIT_BRANCH_NAME }}
      #     echo ${{ github.ref_name }}

      # run the action
      - name: Run publish-docker
        id: run-publish-docker
        uses: lucenelletenebre/publish-docker@main
        with:
          docker-context: ./test
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          docker-image: ghcr.io/lucenelletenebre/test
          docker-platforms: linux/amd64

      # download the just created and uploaded image
      - name: RUN "Hello world" container
        if: success()
        id: test-data
        run: |
          TAG=${{ steps.run-publish-docker.outputs.version-tag }}
          RES=$(docker run --rm ghcr.io/lucenelletenebre/test:${TAG:1})
          echo "::set-output name=value::$RES"
      
      # verify that the container works as expected
      - name: Verify results
        if: success()
        uses: nick-fields/assert-action@v1
        with:
          expected: Hello_World_from_action
          actual: ${{ steps.test-data.outputs.value }}
          comparison: exact
      