---
name: Test Code Base

on:
  push:
    branches: [master, main]
    # branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  # pull_request:
  #   branches: [master, main]

  workflow_dispatch:

jobs:
  test:
    # Name the Job
    name: Test action behaviour
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - name: Run publish-docker
        id: run-publish-docker
        uses: lucenelletenebre/publish-docker@main
        with:
          docker-context: ./test
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          docker-image:  ghcr.io/lucenelletenebre/test

      # - name: Print version number
      #   run: |
      #     MYTAG=${{ steps.run-publish-docker.outputs.version-tag}}
      #     echo $MYTAG

      - name: RUN "Hello world" container
        run: docker run --rm ghcr.io/lucenelletenebre/test:${{ env.TAGVERSION }}